### ISSUE TITLE
Whois command with details

### ISSUE THREAD

**Issue by lcharpenwi6labs** [JoelBender/BACpypes3#8]
Hello.
I am new in Bacnet. I used to visualize data with Yabe. I created a dummy network.
Yabe sends a broadcast whois when a session starts. Here is how it is diplayed :

![image](https://github.com/JoelBender/BACpypes3/assets/7817007/4d2b1f7b-ed61-4267-b9e1-998f109e60bb)

Some information like the name of the device are displayed.

When I send the same request with BACpypes3, I have the response:

```
python3 -m bacpypes3 --address 172.18.0.1/16:47809 --bbmd 172.18.255.255 172.18.255.255 
>whois
260001 172.18.0.2
260002 2710:0x03f7a2
```

Is there a way with BACpypes to have the same kind of information ?

Thanks for your help.

**Comment by JoelBender** [comment]
After the Who-Is is sent and the I-Am's are received, Yabe is using Read-Property to get the device name for the display.  You can do the same thing in your applications, maybe starting out with the **discover-devices.py** sample and adding a call to `app.read_property()` for the `object-name` property of the device object like there is one for the `description`.
